

POST http://localhost:8080/user/signup
Content-Type: application/json 

{
    "username" : "tochiamanzee",
    "email" : "cdonn@gmail.com",
    "password" : "tochi12345"
}

###
POST http://localhost:8080/user/login
Content-Type: application/json 

{
    "username" : "xiiomaryy",
    "password" : "Xiomary331!"
}

###
GET http://localhost:8081/user/getAll

###
PUT http://localhost:8081/editUser/65a2bf5123aa136f896c08d6

Content-Type: application/json 

{
    "bio": "hey"
}

###
GET http://localhost:8081/user/getUserById/65a2bf5123aa136f896c08d6


###
POST  http://localhost:8081/user/deleteAll

###
POST http://localhost:8081/comment/add
Content-Type: application/json

{
    "username": "allanbrock",
    "stationName": "northstation",
    "comment": "fantastic"
}

###
GET http://localhost:8081/comment/getAll
Content-Type: application/json

{
    
}

###
POST http://localhost:8081/comment/editComment
Content-Type: application/json

{
   "_id":"643e8daaa57ef1afb33ec1ca",
    "username":"xio",
    "comment":"hiiii",
    "stationName":"bayline"
}

###
POST http://localhost:8081/recipe/add
Content-Type: application/json

{
    "title": "Sample Recipe Title",
    "ingredients": ["Ingredient 1", "Ingredient 2", "Ingredient 3"],
    "instructions": ["Step 1", "Step 2", "Step 3"],
    "imageUrl": "",
    "cuisineType": "Spanish",
    "userId": "643e8daaa57ef1afb33eb1ca"
}


###
GET http://localhost:8081/recipe/getAll
Content-Type: application/json

{
    
}



###
//get user by id
GET http://localhost:8081/user/getUserById/6604a16c42ab6c0cc27f47c2


###
POST http://localhost:8081/recipe/rateRecipe/65c6b812975faa073a532458

###
//get recipe by id

GET http://localhost:8081/recipe/65c6b812975faa073a532458
Content-Type: application/json


###
POST http://localhost:8081/ratings/add/65c6b7a9975faa073a532454
Content-Type: application/json

{
  "username": "xiomary33",
  "score":5
}

###
//get all ratings
GET http://localhost:8081/ratings/getAll

###
GET http://localhost:8081/ratings/average/65c6b7a9975faa073a532454




###
PUT http://localhost:8080/ratings/editRating
Content-Type: application/json

{
  "recipeId": "65c6b7a9975faa073a532454",
  "newRating": 5
}



###
DELETE 

###
PUT http://localhost:8081/recipe/edit/660445118880b7515243204a
Content-Type: application/json

{
    "title": "hi",
    "ingredients": ["Ingredient 1", "Ingredient 2", "Ingredient 3"],
    "instructions": ["Step 1", "Step 2", "Step 3"],
    "cuisineType": "Spanish"
}

###
PUT http://localhost:8081/ratings/add/65deb071382394dc749d4f9c
Content-Type: application/json

{
  "score": 5
}



###
GET http://localhost:8081/recipe/owner/65a2bf5123aa136f896c08d6
Content-Type: application/json

{
    
}


###

POST http://localhost:8081/comment/addComment/65a2bf5123aa136f896c08d6
Content-Type: application/json

{
    "content": "Your comment content here"
}




###
GET http://localhost:8081/recipe/recipes/search
Content-Type: application/json

{
    
}


###
GET http://localhost:8081/user/getProfile/661ad7f3a35389d6d3c448b0

@base_url = http://localhost:8081

### Search for recipes by title ###
GET {{base_url}}/recipe/recipes/search?title=Tomato Soup

### Search for recipes by ingredients ###
GET {{base_url}}/recipe/recipes/search?ingredients=Tomato
### Search for recipes by 
### Search for recipes by cuisine type ###
GET {{base_url}}/recipe/recipes/search?cuisineType=American
