POST http://localhost:8080/user/signup
Content-Type: application/json 

{
    "username" : "tochiamanze",
    "email" : "cdon@gmail.com",
    "password" : "tochi12345"
}

###

POST http://localhost:8080/user/login
Content-Type: application/json 

{
    "username" : "tochiamanze",
    "password" : "tochi12345"
}

###
GET http://localhost:8081/user/getAll


###
POST http://localhost:8081/user/editUser
Content-Type: application/json 

{
    "userId" : "635ab8dfc407faf9f73deaf2",
    "username" : "Tochi Edit",
    "password" : "dwwrwr"
}

###
GET http://localhost:8081/user/getUserById/65a2bf5123aa136f896c08d6


###
POST  http://localhost:8081/user/deleteAll

###
POST http://localhost:8081/comment/add
Content-Type: application/json

{
    "username": "allanbrock",
    "stationName": "northstation",
    "comment": "fantastic"
}

###
GET http://localhost:8081/comment/getAll
Content-Type: application/json

{
    
}

###
POST http://localhost:8081/comment/editComment
Content-Type: application/json

{
   "_id":"643e8daaa57ef1afb33ec1ca",
    "username":"xio",
    "comment":"hiiii",
    "stationName":"bayline"
}

###
POST http://localhost:8081/recipe/add
Content-Type: application/json

{
    "title": "Sample Recipe Title",
    "ingredients": ["Ingredient 1", "Ingredient 2", "Ingredient 3"],
    "instructions": ["Step 1", "Step 2", "Step 3"],
    "imageUrl": "",
    "cuisineType": "Spanish",
    "userId": "643e8daaa57ef1afb33eb1ca"
}


###
GET http://localhost:8081/recipe/recipeGetAll
Content-Type: application/json

{
    
}



###
//get user by id
GET http://localhost:8081/user/getUserById/65c6c232e44dab5f1004c318

###
PUT http://localhost:8081/recipe/edit/65c6b72f975faa073a53244d

Content-Type: application/json

{
  "title": "Sample Recipe Title",
    "ingredients": ["Ingredient 1", "Ingredient 2", "Ingredient 3"],
    "instructions": ["Step 1", "Step 2", "Step 3"],
    "imageUrl": "",
    "cuisineType": "Spanish",
}

//rating a recipe
POST http://localhost:8081/recipe/rateRecipe/65c6b812975faa073a532458

###
//get recipe by id

GET http://localhost:8081/recipe/65c6b812975faa073a532458
Content-Type: application/json


###
POST http://localhost:8081/ratings/add/65c6b812975faa073a532458
Content-Type: application/json

{
  "username": "xiomary33",
  "score": 3
}

###
//get all ratings
GET http://localhost:8081/ratings/getAll


